# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/caesar.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os
os.environ['QT_QPA_PLATFORM_PLUGIN_PATH'] = '../'

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(310, 10, 111, 16))
        self.label.setObjectName("label")
        self.txt_plain_text = QtWidgets.QLabel(self.centralwidget)
        self.txt_plain_text.setGeometry(QtCore.QRect(40, 110, 61, 16))
        self.txt_plain_text.setObjectName("txt_plain_text")
        self.txt_key = QtWidgets.QLabel(self.centralwidget)
        self.txt_key.setGeometry(QtCore.QRect(40, 230, 61, 16))
        self.txt_key.setObjectName("txt_key")
        self.txt_cipher_text = QtWidgets.QLabel(self.centralwidget)
        self.txt_cipher_text.setGeometry(QtCore.QRect(40, 290, 71, 16))
        self.txt_cipher_text.setObjectName("txt_cipher_text")
        self.btn_encrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btn_encrypt.setGeometry(QtCore.QRect(190, 420, 93, 28))
        self.btn_encrypt.setObjectName("btn_encrypt")
        self.btn_decrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btn_decrypt.setGeometry(QtCore.QRect(570, 420, 93, 28))
        self.btn_decrypt.setObjectName("btn_decrypt")
        self.plain_TextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plain_TextEdit.setGeometry(QtCore.QRect(190, 100, 471, 87))
        self.plain_TextEdit.setObjectName("plain_TextEdit")
        self.plain_TextEdit_2 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plain_TextEdit_2.setGeometry(QtCore.QRect(190, 220, 471, 41))
        self.plain_TextEdit_2.setObjectName("plain_TextEdit_2")
        self.plain_TextEdit_3 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plain_TextEdit_3.setGeometry(QtCore.QRect(190, 290, 471, 87))
        self.plain_TextEdit_3.setObjectName("plain_TextEdit_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "CAESAR CIPHER"))
        self.txt_plain_text.setText(_translate("MainWindow", "Plain Text:"))
        self.txt_key.setText(_translate("MainWindow", "Key::"))
        self.txt_cipher_text.setText(_translate("MainWindow", "CipherText:"))
        self.btn_encrypt.setText(_translate("MainWindow", "Encrypt"))
        self.btn_decrypt.setText(_translate("MainWindow", "Decrypt"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
